// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function AddFiles(arg1, arg2) {
  return window['go']['main']['App']['AddFiles'](arg1, arg2);
}

export function Backup(arg1) {
  return window['go']['main']['App']['Backup'](arg1);
}

export function Backups(arg1) {
  return window['go']['main']['App']['Backups'](arg1);
}

export function ChooseDir() {
  return window['go']['main']['App']['ChooseDir']();
}

export function ChooseFiles() {
  return window['go']['main']['App']['ChooseFiles']();
}

export function Files(arg1) {
  return window['go']['main']['App']['Files'](arg1);
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function RemoveFile(arg1, arg2) {
  return window['go']['main']['App']['RemoveFile'](arg1, arg2);
}

export function RemoveOne(arg1, arg2) {
  return window['go']['main']['App']['RemoveOne'](arg1, arg2);
}

export function Restore(arg1, arg2) {
  return window['go']['main']['App']['Restore'](arg1, arg2);
}

export function Root() {
  return window['go']['main']['App']['Root']();
}
