// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<void>;

export function AddFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function Backup(arg1:string):Promise<any>;

export function Backups(arg1:string):Promise<Array<string>>;

export function ChooseDir():Promise<string>;

export function ChooseFiles():Promise<Array<string>>;

export function Files(arg1:string):Promise<Array<string>>;

export function List():Promise<Array<string>>;

export function Open(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function Remove(arg1:string):Promise<void>;

export function RemoveFile(arg1:string,arg2:string):Promise<void>;

export function RemoveOne(arg1:string,arg2:string):Promise<void>;

export function Rename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Restore(arg1:string,arg2:string):Promise<void>;

export function Root():Promise<string>;
